name: Run on Push & Pull #disabled

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # assuming you have a requirements.txt file
      - name: Run generate_data_live.py script
        run: python generate_data_live.py
        env:
          CLICKHOUSE_HOST: ${{ vars.CLICKHOUSE_HOST }}
          CLICKHOUSE_PORT: ${{ vars.CLICKHOUSE_PORT }}
          CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
          CLICKHOUSE_DATABASE: ${{ vars.CLICKHOUSE_DATABASE }}
          CLICKHOUSE_TABLE: ${{ vars.CLICKHOUSE_TABLE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
      - name: Run main_live script
        run: python main_live.py
        env:
          CLICKHOUSE_HOST: ${{ vars.CLICKHOUSE_HOST }}
          CLICKHOUSE_PORT: ${{ vars.CLICKHOUSE_PORT }}
          CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
          CLICKHOUSE_DATABASE: ${{ vars.CLICKHOUSE_DATABASE }}
          CLICKHOUSE_TABLE: ${{ vars.CLICKHOUSE_TABLE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
